version: '0.0.1'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:13.0.1
    ports:
      - 0.0.0.0:8100:8443
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: '${DATABASE_ADDRESS}'
      DB_PORT: ${DATABASE_PORT}
      DB_DATABASE: '${DATABASE_NAME_KEYCLOAK}'
      DB_USER: '${DATABASE_USERNAME}'
      DB_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - keycloak-config.json:/opt/jboss/keycloak/imports/geocode.json
      - ../.certificates/fullchain.pem:/etc/x509/https/tls.crt
      - ../.certificates/privkey.pem:/etc/x509/https/tls.key
  spring:
    container_name: spring
    image: geocode/backend
    ports:
      - 0.0.0.0:8080:8080
    environment:
      DATABASE_URL: 'jdbc:postgresql://${DATABASE_ADDRESS}:${DATABASE_PORT}/${DATABASE_NAME_GEOCODE}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_AUTH_SERVER_URL: '${KEYCLOAK_AUTH_SERVER_URL}'
      KEYCLOAK_CLIENT_ID: '${KEYCLOAK_CLIENT_ID}'
      WEB_REFERRER: '${WEB_REFERRER}'
      KEY_STORE_TYPE: '${KEY_STORE_TYPE}'
      KEY_STORE: '${KEY_STORE}'
      KEY_STORE_ALIAS: '${KEY_STORE_ALIAS}'
      KEY_STORE_PASSWORD: '${KEY_STORE_PASSWORD}'
