/**
 * Swagger GeoCode
 * This is the swagger documentation and API for the GeoCode project implemented by Peak Performers for the client [5DT](https://5dt.com/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: peakperformers@geocodeapp.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Collectable } from './collectable';
import { GeoCode } from './geoCode';

export interface User { 
    id?: string;
    username: string;
    currentCollectable?: Collectable;
    foundCollectables?: Array<Collectable>;
    foundGeocodes?: Array<GeoCode>;
    myGeocodes?: Array<GeoCode>;
}