# Clones the application to the GeoCode server on push.

name: Remote SSH Commands

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Automatic Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Ionic and Spring Boot applications
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_ADDRESS}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: ${{secrets.SSH_PORT}}
        script: |
          rm -rf GeoCode
          git clone git@github.com:COS301-SE-2021/GeoCode.git
          cd GeoCode
          bash deploy.sh
