# Clones the application to the GeoCode server on push.

name: Remote SSH Commands

on:
  push:
    branches: [ dev/Configuration ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Spring Boot app
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_ADDRESS}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: ${{secrets.SSH_PORT}}
        script: |
          rm -rf GeoCode
          git clone git@github.com:COS301-SE-2021/GeoCode.git
          cd GeoCode/backend
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=geocode/backend
          docker stop spring
          cd ..
          docker-compose --env-file ../.env up -d
          echo "Deployment completed successfully"
