# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Unit Tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: Maven Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.11'
        distribution: 'adopt'
        
    - name: Prevent integration tests from running
      run: |
        tr '\n' ' ' < backend/pom.xml > temp.xml
        sudo sed -i "s/<!-- Integration tests -->.*<!-- End integration tests -->//g" temp.xml
        mv temp.xml backend/pom.xml
        
    - name: Compile application
      run: |
        cd backend
        mvn compile
        
    - name: Run tests
      run: |
        cd backend
        mvn clean verify