# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Maven Integration Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.11'
        distribution: 'adopt'
        
    - name: Set up keystore
      run: |
        openssl req -x509 -out localhost.crt -keyout localhost.key -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' -extensions EXT -config <(printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
        openssl pkcs12 -export -name localhost -password pass:password -in localhost.crt -inkey localhost.key -out keystore.p12
        mv keystore.p12 backend/src/main/resources
        
    - name: Prevent unit tests from running
      run: |
        tr '\n' '\t' < backend/pom.xml > temp.xml
        sudo sed -i "s/<!-- Unit tests -->.*<!-- End unit tests -->//g" temp.xml
        tr '\t' '\n' < temp.xml > backend/pom.xml
        
    - name: Compile application
      run: |
        cd backend
        mvn compile
        
    - name: Run tests
      run: |
        cd backend
        mvn clean verify \
          -Denv.DATABASE_URL=${{secrets.TEST_DATABASE_URL}} \
          -Denv.DATABASE_USERNAME=${{secrets.TEST_DATABASE_USERNAME}} \
          -Denv.DATABASE_PASSWORD=${{secrets.TEST_DATABASE_PASSWORD}} \
          -Denv.WEB_REFERRER="http://localhost" \
          -Denv.KEY_STORE_TYPE=PKCS12 \
          -Denv.KEY_STORE=classpath:keystore.p12 \
          -Denv.KEY_STORE_ALIAS=localhost \
          -Denv.KEY_STORE_PASSWORD=password