name: Type Script CI

on:
  push:
    branches: [ master, development, dev/Configuration ]
  pull_request:
    branches: [ master, development, dev/Configuration ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
            cd frontend
            npm cache clean --force
            npm install
            npm ci
            npm run build --if-present
            npm test