name: TypeScript CI

on:
  push:
    branches: [ master, development, dev/App ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: TypeScript Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up files that usually contain environment variables
        run: |
            cd frontend/src
            cp environments/environment.prod.ts environments/environment.ts

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.17.5'
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli@12.2.1
        
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli@6.17.0

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build app
        working-directory: ./frontend
        run: ionic build

  frontend-tests:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up files that usually contain environment variables
        run: |
            cd frontend/src
            cp environments/environment.prod.ts environments/environment.ts

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.17.5'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@12.2.1
        
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli@6.17.0

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: ng test --watch false --browsers=ChromeHeadless