/**
 * Swagger GeoCode
 * This is the swagger documentation and API for the GeoCode project implemented by Peak Performers for the client [5DT](https://5dt.com/).
 *
 * OpenAPI spec version: 1.5.18
 * Contact: peakperformers@geocodeapp.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The GeoCode's real world locating difficulty
 */
export type Difficulty = 'EASY' | 'MEDIUM' | 'HARD' | 'INSANE';

export const Difficulty = {
    EASY: 'EASY' as Difficulty,
    MEDIUM: 'MEDIUM' as Difficulty,
    HARD: 'HARD' as Difficulty,
    INSANE: 'INSANE' as Difficulty
};