/**
 * Swagger GeoCode
 * This is the swagger documentation and API for the GeoCode project implemented by Peak Performers for the client [5DT](https://5dt.com/).
 *
 * OpenAPI spec version: 1.5.8
 * Contact: peakperformers@geocodeapp.tech
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The types of Missions
 */
export type MissionType = 'Circumference' | 'GeoCode' | 'Swap' | 'Random';

export const MissionType = {
    Circumference: 'Circumference' as MissionType,
    GeoCode: 'GeoCode' as MissionType,
    Swap: 'Swap' as MissionType,
    Random: 'Random' as MissionType
};